image: node:13.8

cache:
  paths:
  - node_modules

stages:
  - install
  - deploy

Install:
  stage: install
  script:
    - npm ci

Deploy:
  stage: deploy
  script: 
    - npm run build --prod
    - rm -rf public
    - mv build public
  artifacts:
    paths:
    - public # Built files for GitLab Pages
  only:
    - master